### ISSUE TITLE
Find a better way to distribute the SDK

### ISSUE THREAD

**Issue by odedhb** [app-central/sdk-unity#1]
Like NPM or Swift Package Manager

**Comment by SabreRunner** [comment]
I've got this. Is this good enough or do we need to refine this?
https://gist.github.com/SabreRunner/a0095ecbce1086a956f3e54303973d93

**Comment by odedhb** [comment]
please add to the readme:

![WhatsApp Image 2020-12-07 at 12 51 36](https://user-images.githubusercontent.com/5231236/101345431-af739b00-388f-11eb-8dc9-c2e23f8578df.jpeg)

**Comment by odedhb** [comment]
Change the api, single class and method calls to match the old one.
