### ISSUE TITLE
Consider: Unity - client side - embedded html for paywall design.

### ISSUE THREAD

**Issue by odedhb** [app-central/sdk-unity#11]

**Comment by SabreRunner** [comment]
I would appreciate more details on these issues. That is, as much as in your brain when you create a task as you can put down. I don't really understand what I'm supposed to do here.

**Comment by odedhb** [comment]
Test if you can put a hard-coded html page inside the paywall in the SDK you built.
Makes sense? @SabreRunner

**Comment by SabreRunner** [comment]
Give me a test link with something to show. This shouldn't be too difficult. Though, this will probably require another 3rd party solution.

**Comment by odedhb** [comment]
Here's an example @SabreRunner 
https://paywalls.s3.amazonaws.com/nextmovies/old_wall_8_2020_nextmovies.html

**Comment by SabreRunner** [comment]
I couldn't find any HTML display solution that is free.
https://assetstore.unity.com/packages/tools/network/uniwebview-4-175993

**Comment by odedhb** [comment]
@SabreRunner it doesn't have to be free.
Go ahead and purchase that under our Unity account.
Remember that the html code should be local on the device.

**Comment by SabreRunner** [comment]
What do you mean that the code should be local?

**Comment by odedhb** [comment]
The html code should not be loaded from a server.
It should be in the code of the client as a local file.
We don't want any communication delay.
@SabreRunner 

Keep in mind this is a research ("consider") task.
So if this looks cumbersome we should abandon this idea.

**Comment by SabreRunner** [comment]
This shouldn't be as long as we have a proper web view package. So, I should buy that one.

**Comment by SabreRunner** [comment]
But, before I go into this, is this just for the design of the subscription dialog? Wouldn't it be better to stick to the standard design and just download specific assets?

**Comment by odedhb** [comment]
That's the actual purpose of the task, to see what's better...
If it looks like using HTML is cumbersome, we should abandon this idea.

**Comment by SabreRunner** [comment]
Yeah. I think the better idea is for the company to decide on a standard design of this background, that foreground, button goes here, title go here, and the developers will upload the images they want and set the text.

**Comment by odedhb** [comment]
@SabreRunner yeah, that's my hunch as well.
But let's do a bit of research before deciding.

**Comment by SabreRunner** [comment]
Ok. Please create new issues for whichever direction you want to proceed.
