### ISSUE TITLE
The code in this method is not DRY

### ISSUE THREAD

**Issue by odedhb** [app-central/sdk-unity#12]
Try to move some of the repeating logic to a function

(DRY - don't repeat yourself)

https://github.com/app-central/Unity-SDK-v2/blob/2423cdd6160e6ee522e62215f9a18ad5d7fcb19c/Runtime/AppCentral/SubscriptionWindow.cs#L73

**Comment by SabreRunner** [comment]
I rechecked my assumptions and refactored the method. Please have another look.

**Comment by odedhb** [comment]
great
https://github.com/app-central/sdk-unity/commit/6e5dad1479a5b9e3a591ad92c4c65c6fb6db4141

**Comment by SabreRunner** [comment]
I can't see a lists of commits to pull from.

**Comment by SabreRunner** [comment]
#266dd462ca100e673d89bff94a82d92bd29d0188

**Comment by SabreRunner** [comment]
[Commit](https://github.com/app-central/sdk-unity/commit/266dd462ca100e673d89bff94a82d92bd29d0188)
