### ISSUE TITLE
Improve SDK usability

### ISSUE THREAD

**Issue by odedhb** [app-central/sdk-unity#14]
Configuration and error throwing.
If the dev didn't configure a plan, throw an error or print a log

**Comment by SabreRunner** [comment]
Just for the plan or for any missing component?

**Comment by odedhb** [comment]
I'm going to check the whole flow and make sure it's easy as pie.

**Comment by odedhb** [comment]
@SabreRunner 
What's the easiest way to give the developer access to configuration?

**Comment by odedhb** [comment]
Is there a way to avoid creation of a configuration file?
Is there some sort of general configuration file that all SDKs have access to?
Something like iOS's infor.plist or android's manifest?

**Comment by SabreRunner** [comment]
You can only do that with a custom solution. If we can assume that having our SDK means all the others must be present, we can maybe work something out that sends out information to all the other SDKs.

**Comment by odedhb** [comment]
What about app.config? @SabreRunner
