### ISSUE TITLE
Create a PaywallPanel.cs class

### ISSUE THREAD

**Issue by odedhb** [app-central/sdk-unity#15]
In the process of migrating the old sdk to the new sdk.
Please create a single class that handles the paywall graphics and send it to me as a file.

**Comment by SabreRunner** [comment]
That's what the SubscriptionWindow.cs and SubscriptionWindowConfiguration.cs are for. Do you want me to change them somehow?

**Comment by odedhb** [comment]
Yes, please combine them into one file.
The file should have a class with a static function that takes all the parameters needed to show the paywall.

**Comment by SabreRunner** [comment]
Updated.
