### ISSUE TITLE
Add all window components to init

### ISSUE THREAD

**Issue by odedhb** [app-central/sdk-unity#16]
https://github.com/app-central/sdk-unity/blob/2ba84cd9fecb8f4a93bfbd1c75f0261252e61bd8/Runtime/AppCentral/SubscriptionWindow.cs#L59

The initializer should receive the title, image, description, etc.

**Comment by SabreRunner** [comment]
Are you sure? That is very limited. The idea is that developers take the prefab and then modify it in their style. The activation should only contain data.

**Comment by odedhb** [comment]
You are right, but we have to make it fool-proof at this point.
We'll be giving the developer copy-paste instructions.
We'll add customizability in future versions.

**Comment by SabreRunner** [comment]
On it.

**Comment by SabreRunner** [comment]
Try it now.

**Comment by odedhb** [comment]
@SabreRunner , ideally, I need something that will be plug&play for me.
Just copy the class to the old SDK, call showPaywall and it will work.

**Comment by SabreRunner** [comment]
> @SabreRunner , ideally, I need something that will be plug&play for me.
> Just copy the class to the old SDK, call showPaywall and it will work.

I'm not sure I understand how that should work. The new UI is much more graphical. It's designed to allow the game developer to use their own art. It's no longer drawing UI from scratch. However, you can still just call it and it will use default values.

**Comment by odedhb** [comment]
@SabreRunner 

The process would start with an email like so:

Hi <developer_name>,
Please add this AppCentral.cs file and this image to your project, and call this function:
AppCentral.setup("subscription_plan_id", "Access all levels", "Subscribe now", "wallpaper.png");

**Comment by SabreRunner** [comment]
That is no longer possible with the new SDK because of the extensive graphical elements.
But, the difference is "Import this package. Drag the desired Subscription Window prefab to your scene. Enable it and call SubscriptionWindow behaviour's Initialise when you want to show it."
