### ISSUE TITLE
Create a document on how to convert a game to WebGL and send it to us

### ISSUE THREAD

**Issue by odedhb** [app-central/sdk-unity#2]

**Comment by SabreRunner** [comment]
1. Switch Platform to WebGL.
2. Disable "Run in Background"
3. Set "API Compatibility Level" to ".NET 4.x"
4. Build and Run.

**Comment by SabreRunner** [comment]
Here's the build.
[Build.zip](https://github.com/app-central/Unity-SDK-v2/files/5651973/Build.zip)

**Comment by SabreRunner** [comment]
This is the [document](https://levelup.gitconnected.com/how-to-publish-your-unity3d-html5-application-or-game-to-aws-3bb053b59d21) except you should use gzip compression instead. Works better.

**Comment by SabreRunner** [comment]
1. Switch Platform to WebGL.
2. Disable "Run in Background"
3. Set "API Compatibility Level" to ".NET 4.x"
4. Set "Compression Format" to "gzip"
5. Build and Run.

**Comment by SabreRunner** [comment]
Birds: https://app-central-webgl-test.s3.eu-central-1.amazonaws.com/BirdGL/index.html
FPS Microgame: https://app-central-webgl-test.s3.eu-central-1.amazonaws.com/FPSMicrogame/index.html
