### ISSUE TITLE
Redesign the SDK

### ISSUE THREAD

**Issue by odedhb** [app-central/sdk-unity#7]
![0EA4B859-8957-4A73-9435-C50C0CE6369E](https://user-images.githubusercontent.com/5231236/102717004-3c830f00-42e8-11eb-9a3a-194d7ca1ac32.png)

**Comment by SabreRunner** [comment]
Tasks:
1. Configuration file for graphics.
2. Default local assets.
3. Copy old GUI graphics template.
4. Third template TBD

**Comment by SabreRunner** [comment]
__**Today**__
Updated dependencies to new IAP.
Rebuilt the subscription window.
Made a prefab.
Finished connecting everything in a new script.
Added configuration file for subscription window.
Rebuilt the old subscription window as it was.

**Comment by SabreRunner** [comment]
![image](https://user-images.githubusercontent.com/10673434/103074057-7e0a0780-45d1-11eb-9f1e-1d4b8aba6280.png)

**Comment by SabreRunner** [comment]
Need to rewire the old window to use the same features as the new one.

**Comment by SabreRunner** [comment]
Connected Old subscription window to definitions behaviour.
Separated canvas from window for more modularity.

**Comment by SabreRunner** [comment]
Anything specific I should be focusing on now?

**Comment by SabreRunner** [comment]
I basically created a prefab for the subscription window. To use it, you drag the prefab into a canvas (which must be the top most one) and then you call SubscriptionWindow.ShowPanel() to show it.

**Comment by odedhb** [comment]
Not sure it's the best way.
But let's decide when we see the full doc.

**Comment by SabreRunner** [comment]
I think I've done all I can with the readme.
We just need other templates now.
