### ISSUE TITLE
Consider a more elegant way of doing this, maybe an array

### ISSUE THREAD

**Issue by odedhb** [app-central/sdk-unity#9]
https://github.com/app-central/Unity-SDK-v2/blob/2423cdd6160e6ee522e62215f9a18ad5d7fcb19c/Runtime/AppCentral/SubscriptionWindow.cs#L131

**Comment by SabreRunner** [comment]
There is no other way of checking that all inspector fields are properly assigned.

**Comment by odedhb** [comment]
Does unity support [Null-conditional operators](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/member-access-operators#null-conditional-operators--and-)?

So this:

            if (this.subscriptionButtonTMP != null)
            {this.subscriptionButtonTMP.text = this.subscriptionConfiguration.subscriptionButtonText;}

can be changed to this:

            this.subscriptionButtonTMP?.text = this.subscriptionConfiguration.subscriptionButtonText;

?

**Comment by odedhb** [comment]
Also, this may be possible with an array and a `[].ForEach(x => { ...; }); `

            if (this.topTitleTMP != null)
            {this.topTitleTMP.alignment = TextAlignmentOptions.Center;}
            if (this.topSubtitleTMP != null)
            {this.topSubtitleTMP.alignment = TextAlignmentOptions.Center;}
            if (this.subscriptionButtonTMP != null)
            {this.subscriptionButtonTMP.alignment = TextAlignmentOptions.Center;}
            if (this.bottomTitleTMP != null)
            {this.bottomTitleTMP.alignment = TextAlignmentOptions.Center;}
            if (this.bottomSubtitleTMP != null)
            {this.bottomSubtitleTMP.alignment = TextAlignmentOptions.Center;}

should be changeable to this:

**Comment by SabreRunner** [comment]
I can collapse the very similar ones into an array but you can't use Null Propagation in assignments.

**Comment by odedhb** [comment]
Great, please attach the commits to this issue

**Comment by SabreRunner** [comment]
[Commit](https://github.com/app-central/sdk-unity/commit/6e5dad1479a5b9e3a591ad92c4c65c6fb6db4141)
